import type { Metadata } from "next";
import { ThemeProvider } from "@/providers/theme-provider";
import { Inter } from "next/font/google";
import "./globals.css";
import TwitchSearchBar from "@/components/search-bars/twitch-search";
import ReactQueryProvider from "@/providers/reactquery-provider";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import Footer from "@/components/layout/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryProvider>
          <ThemeProvider attribute="class" defaultTheme="dark" enableSystem disableTransitionOnChange>
            <main className="w-[1600px] mx-auto">
              <TwitchSearchBar />
              <div className="mt-4">{children}</div>
            </main>
            <Footer />
          </ThemeProvider>
          <ReactQueryDevtools />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
